services:
  - type: web
    name: douyin-fb-webapp
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python web/app.py
